mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('write/', views.write, name='post_write'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('<int:pk>/new_comment/', views.new_comment, name='new_comment'),
    path('update_comment/<int:pk>/', views.update_comment, name='update_comment'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('category/<str:slug>/', views.category_page, name='category_page'),
    path('tag/<str:slug>/', views.tag_page, name='tag_page'),
]

mysite/tutorialblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
# from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    head_image = models.ImageField(
        upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(
        upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)

    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    
    tags = models.ManyToManyField('tag', blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    def get_file_name(self):
        return self.file_upload.name.split('/')[-1]
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    

class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, allow_unicode=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'
        
    class Meta:
        verbose_name_plural = 'Categories'


class Tag(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, allow_unicode=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'
        

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'[{self.post}] {self.content} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.post.pk}/#comment-{self.pk}'
    
    class Meta:
        ordering = ['-id']

mysite/blog/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Category, Tag, Comment
from .forms import CommentForm
from django.utils.text import slugify
from django.db.models import Q

class PostList(ListView):
    model = Post
    ordering = '-pk'
    # template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        context['category_list']= Category.objects.all().order_by('-name')
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()
        search_keyword = self.request.GET.get('q')

        if search_keyword:
            # queryset = queryset.filter(title__icontains=search_keyword)
            queryset = queryset.filter(
                Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(tags__name__icontains=search_keyword)).distinct()
            
        return queryset
    
class Postdetail(DetailView):
    model = Post
    # template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super(Postdetail, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('-name')
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()
        context['comment_form'] = CommentForm
        return context
    

def category_page(request, slug):
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all().order_by('-name')
    context = {
        'blog_list': Post.objects.filter(category=category).order_by('-pk'),
        'categories': categories,
        'no_category_post_count': Post.objectsfilter(category=None).count(),
        'category': category,
        'category_list': Category.objects.all().order_by('-name'),
    }
    return render(request, 'blog/post_list.html', context)

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    print(tag)
    post_list = tag.post_set.all()
    categories = Category.objects.all().order_by('-name')
    context = {
        'post_list': post_list,
        'categories': categories,
        'no_category_post_count': Post.objects.filter(category=None).count(),
        'tag': tag,
        'category_list': Category.objects.all().order_by('-name'),
    }
    return render(request, 'blog/blog_list.html', context)


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload', 'category']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            # 기존에 리턴하던 값을 response에 담아둠
            response = super(write, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/')
        

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload', 'category', 'tags']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostUpdate, self).form_valid(form)
        else:
            return redirect('/blog/')
        
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            post = self.get_object()
            if post.author == request.user:
                return super().dispatch(request, *args, **kwargs)
            else:
                return HttpResponse('You are not allowed to update this post')
            
        return super().dispatch(request, *args, **kwargs)
    

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = Post.objects.get(pk=pk)
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                # commit=Falser를 하면, db에 바로 저장되지 않고, 메모리에 객체 하나 생성해줌.
                comment = form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                form = CommentForm()
            return render(request, 'blog/comment_form.html', {'form': form})
        

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(CommentUpdate, self).form_valid(form)
        else:
            return redirect('/blog/')
        
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            comment = self.get_object()
            if comment.author == request.user:
                return super().dispatch(request, *args, **kwargs)
            else:
                return HttpResponse('You are not allowed to update this comment')
        return super().dispatch(request, *args, **kwargs)
    

def delete_comment(request, pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=pk)
        if comment.author == request.user:
            comment.delete()
            return redirect(comment.post.get_absolute_url())
        else:
            return HttpResponse('You ar not allowed to delete this comment')
    return redirect('/blog/')

post_list = PostList.as_view()
write = PostCreate.as_view()
edit = PostUpdate.as_view()
delete = DeleteView.as_view()
update_comment = CommentUpdate.as_view()

mysite/templates/blog/comment_form.html
<!DOCTYPE html>
<html lang="ko-KR">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <h1>edit comment</h1>
    <form method="post">
        {% csrf_token %}
        <table class="table">
            {{form}}
        </table>
        <button type="submit">작성</button>
    </form>
  </body>
</html>

mysite/templates/blog/post_detail.html
post_detail

mysite/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Toast Editor 2.0.0과 의존성 -->
    <link
        rel="stylesheet"
        href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"
    />
    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            {{form}}
            <tr>
                <th><label for="id_tags">Tags:</label></th>
                <td><input type="text" name="tags_str" id="id_tags_str"></td>
            </tr>
            <tr>
                <th><label for="id_content_editor">Content_editor:</label></th>
                <td><div id="editor"></div></td>
            </tr>
        </table>
        <button type="submit" id="submitbtn">제출</button>
    </form>
    <script>
        const Editor = toastui.Editor;

        const editor = new Editor({
            el: document.querySelector("#editor"),
            height: "600px",
            initialEditType: "markdown",
            previewStyle: "vertical",
        });

        // editor.getHTML()
        // editor.getMarkdown()
        document.getElementById('submitbtn').addEventListener('click', function(){
            const markdownContent = editor.getMarkdown();
            document.getElementById('id_content').value = markdownContent;
        });
    </script>
</body>
</html>

mysite/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="ko-KR">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    { % for i in posts % }
        <p>{{ i.title }}</p>
        <p>{{ i.content }}</p>
        <p>{{ i.created_at }}</p>
    { % endfor %}

  </body>
</html>

mysite/templates/blog/write.html
<!DOCTYPE html>
<html lang="ko-KR">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글쓰기</title>
  <link rel="stylesheet" href="./css/common.css">
  <link rel="stylesheet" href="./css/table.css">
  <link rel="stylesheet" href="./css/write.css">

</head>

<body>
  <!-- header -->
  <div class="header">
    <h1><a href="index.html">HTML/CSS 실습</a></h1>
    <div class="header-click">
      <a href="chat.html">채팅</a>
      <a href="login.html">로그인</a>
      <a href="join.html">회원가입</a>
      <button type="button">로그아웃</button>
    </div>
  </div>
  <!-- // header -->

  <div class="main">
    <!-- 글쓰기 페이지 -->
    <h2 class="main-title">글쓰기</h2>
    <p class="main-desc">내용을 입력 해주세요.</p>

    <form>
      <table class="table write">
        <colgroup>
          <col style="width: 120px">
          <col>
        </colgroup>
        <tbody>
          <tr>
            <th><label for="category">카테고리</label></th>
            <td>
              <select id="category">
                <option value="1">일반</option>
                <option value="2">공지사항</option>
              </select>
            </td>
          </tr>
          <tr>
            <th><label for="board-title">제목</label></th>
            <td><input type="text" id="board-title" name="boardTitle"></td>
          </tr>
          <tr>
            <th><label for="board-content">내용</label></th>
            <td>
              <textarea id="board-content"></textarea>
            </td>
          </tr>
          <tr>
            <th><label for="board-file">파일첨부</label></th>
            <td>
              <input type="file" id="board-file">
            </td>
          </tr>
        </tbody>
      </table>
      <div class="btn-group">
        <a href="./index.html" class="btn">목록</a>
        <button type="reset" class="btn">초기화</button>
        <button type="submit" class="btn">작성</button>
      </div>
    </form>

    <!--  //글쓰기 페이지 -->
  </div>

  <!-- footer -->
  <p class="footer">Copyright 2023. Chilli All rights reserved.</p>
  <!-- //footer -->
</body>

</html>